name: theteam_gateway_service
description: A TheTeam Gateway Micro Service.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  grpc: ^3.1.0
  get_it: ^7.2.0
  injectable: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.4
