trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'DipDev Server'
    runOptions: 'commands'
    commands: 'cd workspace && cd musmula_backend && git reset --hard HEAD && git checkout main && git pull origin main && docker-compose up -d --build && exit'
    readyTimeout: '20000'
    failOnStdErr: false