version: '3.5'

services:
  service_gateway:
    container_name: service_gateway
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'
    env_file:
      - .env
    environment:
      - PORT=$GATEWAY_PORT
      - USER_SERVICE_IP=service_user
      - USER_SERVICE_PORT=$USER_SERVICE_PORT
      - ACTIVITY_SERVICE_IP=service_activity
      - ACTIVITY_SERVICE_PORT=$ACTIVITY_SERVICE_PORT
    build:
      dockerfile: ./gateway_service/Dockerfile
      context: '.'
    restart: always
    networks:
      - network

  service_user:
    container_name: service_user
    expose:
      - $USER_SERVICE_PORT
    environment:
      - PORT=$USER_SERVICE_PORT
      - ADDRESS_EMAIL=$ADDRESS_EMAIL
      - PASSWORD_EMAIL=$PASSWORD_EMAIL
      - SMTP_ADDRESS_EMAIL=$SMTP_ADDRESS_EMAIL
      - SMTP_PORT_EMAIL=$SMTP_PORT_EMAIL
      - DB_DIRECTORY=/app/db
    build:
      dockerfile: ./user_service/Dockerfile
      context: '.'
    volumes:
      - auth_db_data:/app/db
    restart: always
    networks:
      - network

  service_activity:
    container_name: service_activity
    expose:
      - $ACTIVITY_SERVICE_PORT
    environment:
      - PORT=$ACTIVITY_SERVICE_PORT
      - DB_DIRECTORY=/app/db
    build:
      dockerfile: ./activity_service/Dockerfile
      context: '.'
    volumes:
      - time_tracking_db_data:/app/db
    restart: always
    networks:
      - network

volumes:
  auth_db_data: {}
  time_tracking_db_data: {}

networks:
  network:
    driver: bridge
