version: '3.5'

services:
  # db_auth:
  #   container_name: db_auth
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=postgres
  #   image: postgres:15.2-alpine
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  service_auth:
    container_name: service_auth
    ports:
      - '8080:8080'
    expose:
      - 8080
    environment:
      - PORT=8080
      - DB_NAME=service_auth_database
      - DB_DIRECTORY=/app/db
    build: ./musmula_auth_service
    volumes:
      - auth_db_data:/app/db
    restart: always

volumes:
   auth_db_data: {}