version: '3.5'

services:
  service_gateway:
    container_name: service_gateway
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'
    env_file:
      - .env
    environment:
      - PORT=$GATEWAY_PORT
      - AUTH_IP=service_auth
      - AUTH_PORT=$AUTH_PORT
      - TIME_TRACKING_IP=service_time_tracking
      - TIME_TRACKING_PORT=$TIME_TRACKING_PORT
    build:
      dockerfile: ./gateway_service/Dockerfile
      context: '.'
    restart: always
    networks:
      - network

  service_auth:
    container_name: service_auth
    expose:
      - $AUTH_PORT
    environment:
      - PORT=$AUTH_PORT
      - ADDRESS_EMAIL=$ADDRESS_EMAIL
      - PASSWORD_EMAIL=$PASSWORD_EMAIL
      - SMTP_ADDRESS_EMAIL=$SMTP_ADDRESS_EMAIL
      - SMTP_PORT_EMAIL=$SMTP_PORT_EMAIL
      - DB_DIRECTORY=/app/db
    build:
      dockerfile: ./auth_service/Dockerfile
      context: '.'
    volumes:
      - auth_db_data:/app/db
    restart: always
    networks:
      - network

  service_time_tracking:
    container_name: service_time_tracking
    expose:
      - $TIME_TRACKING_PORT
    environment:
      - PORT=$TIME_TRACKING_PORT
      - DB_DIRECTORY=/app/db
    build:
      dockerfile: ./time_tracking_service/Dockerfile
      context: '.'
    volumes:
      - time_tracking_db_data:/app/db
    restart: always
    networks:
      - network

volumes:
  auth_db_data: {}
  time_tracking_db_data: {}

networks:
  network:
    driver: bridge
