name: musmula_auth_service
description: A Musmula Auth Micro Service.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  grpc: ^3.1.0
  dart_jsonwebtoken: ^2.7.1
  objectbox: ^1.7.2
  get_it: ^7.2.0
  injectable: ^2.1.0
  crypto: ^3.0.2
  built_value: ^8.4.4
  built_collection: ^5.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  objectbox_generator: ^1.7.2
  injectable_generator: ^2.1.4
  built_value_generator: ^8.4.4
